import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Background Image Remover</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto flex min-h-screen overflow-hidden'>
        <h1>Upload Image</h1>
        {/* Image Upload Component */}
      </main>
    </>
  )
}
